// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agora.proto

package agorapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Filter is a simple key/value predicate applied against document metadata
// (e.g. {"jurisdiction": "us-senate"}). Empty filters match all documents.
type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_agora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// SearchRequest is issued by a client to the coordinator, and fanned out by the
// coordinator to each worker. `top_k` bounds the number of results a worker
// returns so that inter-node payloads stay small.
type SearchRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Query   string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK    int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Filters []*Filter              `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	// Optional trace/correlation id propagated across the scatter-gather path.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_agora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// SearchResult is a single ranked document hit produced by a worker.
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`                              // BM25 relevance score.
	TextSnippet   string                 `protobuf:"bytes,3,opt,name=text_snippet,json=textSnippet,proto3" json:"text_snippet,omitempty"` // Short excerpt for client display.
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                // Worker/shard that produced this hit.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_agora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResult) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetTextSnippet() string {
	if x != nil {
		return x.TextSnippet
	}
	return ""
}

func (x *SearchResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// SearchResponse carries the ranked hits plus timing metadata. Workers return
// their local top-K; the coordinator merges these into a global top-K.
type SearchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Results         []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	ExecutionTimeMs int64                  `protobuf:"varint,2,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// Nodes that actually contributed results (useful under partial failure).
	ServedBy []string `protobuf:"bytes,3,rep,name=served_by,json=servedBy,proto3" json:"served_by,omitempty"`
	// Nodes that were expected but timed out or errored (empty on full success).
	DegradedNodes []string `protobuf:"bytes,4,rep,name=degraded_nodes,json=degradedNodes,proto3" json:"degraded_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_agora_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *SearchResponse) GetServedBy() []string {
	if x != nil {
		return x.ServedBy
	}
	return nil
}

func (x *SearchResponse) GetDegradedNodes() []string {
	if x != nil {
		return x.DegradedNodes
	}
	return nil
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the caller (coordinator) requesting the check.
	RequesterId   string `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agora_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type HealthCheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Active          bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	DocumentCount   int64                  `protobuf:"varint,3,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agora_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HealthCheckResponse) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *HealthCheckResponse) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// Heartbeat is pushed by a worker to the coordinator on an interval so the
// coordinator can maintain liveness without polling every node.
type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address         string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // host:port the worker's SearchService listens on.
	Active          bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	DocumentCount   int64                  `protobuf:"varint,4,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agora_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Heartbeat) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Heartbeat) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *Heartbeat) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type HeartbeatAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Coordinator-suggested next heartbeat interval in milliseconds.
	NextIntervalMs int64 `protobuf:"varint,2,opt,name=next_interval_ms,json=nextIntervalMs,proto3" json:"next_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_agora_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_agora_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_agora_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatAck) GetNextIntervalMs() int64 {
	if x != nil {
		return x.NextIntervalMs
	}
	return 0
}

var File_agora_proto protoreflect.FileDescriptor

const file_agora_proto_rawDesc = "" +
	"\n" +
	"\vagora.proto\x12\bagora.v1\"0\n" +
	"\x06Filter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x85\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12*\n" +
	"\afilters\x18\x03 \x03(\v2\x10.agora.v1.FilterR\afilters\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"w\n" +
	"\fSearchResult\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12!\n" +
	"\ftext_snippet\x18\x03 \x01(\tR\vtextSnippet\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\xb2\x01\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.agora.v1.SearchResultR\aresults\x12*\n" +
	"\x11execution_time_ms\x18\x02 \x01(\x03R\x0fexecutionTimeMs\x12\x1b\n" +
	"\tserved_by\x18\x03 \x03(\tR\bservedBy\x12%\n" +
	"\x0edegraded_nodes\x18\x04 \x03(\tR\rdegradedNodes\"7\n" +
	"\x12HealthCheckRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"\x99\x01\n" +
	"\x13HealthCheckResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12%\n" +
	"\x0edocument_count\x18\x03 \x01(\x03R\rdocumentCount\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\"\xa9\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12%\n" +
	"\x0edocument_count\x18\x04 \x01(\x03R\rdocumentCount\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs\"T\n" +
	"\fHeartbeatAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12(\n" +
	"\x10next_interval_ms\x18\x02 \x01(\x03R\x0enextIntervalMs2L\n" +
	"\rSearchService\x12;\n" +
	"\x06Search\x12\x17.agora.v1.SearchRequest\x1a\x18.agora.v1.SearchResponse2\x95\x01\n" +
	"\rHealthService\x12D\n" +
	"\x05Check\x12\x1c.agora.v1.HealthCheckRequest\x1a\x1d.agora.v1.HealthCheckResponse\x12>\n" +
	"\x0fReportHeartbeat\x12\x13.agora.v1.Heartbeat\x1a\x16.agora.v1.HeartbeatAckB4Z2github.com/cadenchuang/agora/proto/agorapb;agorapbb\x06proto3"

var (
	file_agora_proto_rawDescOnce sync.Once
	file_agora_proto_rawDescData []byte
)

func file_agora_proto_rawDescGZIP() []byte {
	file_agora_proto_rawDescOnce.Do(func() {
		file_agora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agora_proto_rawDesc), len(file_agora_proto_rawDesc)))
	})
	return file_agora_proto_rawDescData
}

var file_agora_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agora_proto_goTypes = []any{
	(*Filter)(nil),              // 0: agora.v1.Filter
	(*SearchRequest)(nil),       // 1: agora.v1.SearchRequest
	(*SearchResult)(nil),        // 2: agora.v1.SearchResult
	(*SearchResponse)(nil),      // 3: agora.v1.SearchResponse
	(*HealthCheckRequest)(nil),  // 4: agora.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: agora.v1.HealthCheckResponse
	(*Heartbeat)(nil),           // 6: agora.v1.Heartbeat
	(*HeartbeatAck)(nil),        // 7: agora.v1.HeartbeatAck
}
var file_agora_proto_depIdxs = []int32{
	0, // 0: agora.v1.SearchRequest.filters:type_name -> agora.v1.Filter
	2, // 1: agora.v1.SearchResponse.results:type_name -> agora.v1.SearchResult
	1, // 2: agora.v1.SearchService.Search:input_type -> agora.v1.SearchRequest
	4, // 3: agora.v1.HealthService.Check:input_type -> agora.v1.HealthCheckRequest
	6, // 4: agora.v1.HealthService.ReportHeartbeat:input_type -> agora.v1.Heartbeat
	3, // 5: agora.v1.SearchService.Search:output_type -> agora.v1.SearchResponse
	5, // 6: agora.v1.HealthService.Check:output_type -> agora.v1.HealthCheckResponse
	7, // 7: agora.v1.HealthService.ReportHeartbeat:output_type -> agora.v1.HeartbeatAck
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agora_proto_init() }
func file_agora_proto_init() {
	if File_agora_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agora_proto_rawDesc), len(file_agora_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agora_proto_goTypes,
		DependencyIndexes: file_agora_proto_depIdxs,
		MessageInfos:      file_agora_proto_msgTypes,
	}.Build()
	File_agora_proto = out.File
	file_agora_proto_goTypes = nil
	file_agora_proto_depIdxs = nil
}
